name: sam2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - pip:
    - absl-py==2.0.0
    - addict==2.4.0
    - aiodns
    - aiofiles
    - aiohttp
    - aiohttp-retry
    - aiosignal
    - albumentations==1.3.0
    - altair==5.2.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.8
    - anyio==3.7.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backoff==2.2.1
    - bcrypt==4.2.0
    - blinker==1.8.2
    - boto3==1.34.147
    - botocore==1.34.147
    - Brotli==1.1.0
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmake==3.28.0
    - colorama==0.4.6
    - contourpy==1.1.1
    - cryptography==43.0.0
    - cycler==0.12.1
    - Cython==3.0.6
    - defusedxml==0.7.1
    - dnspython==2.6.1
    - einops==0.3.0
    - email_validator==2.2.0
    - exceptiongroup==1.2.0
    - fastapi==0.105.0
    - fastapi-cli==0.0.4
    - ffmpy==0.3.1
    - filelock==3.13.1
    - fonttools==4.46.0
    - frozenlist==1.4.0
    - fsspec==2023.12.2
    - ftfy==6.1.3
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - gitdb==4.0.11
    - GitPython==3.1.43
    - google-auth==2.25.2
    - google-auth-oauthlib==1.0.0
    - gradio==3.39.0
    - gradio_client==0.7.2
    - greenlet==3.0.3
    - grpcio==1.60.0
    - h11==0.14.0
    - httpcore==1.0.2
    - httptools==0.6.1
    - httpx==0.25.2
    - huggingface-hub==0.19.4
    - idna==3.6
    - imageio==2.33.1
    - importlib-metadata==7.0.0
    - importlib-resources==6.4.2
    - inquirerpy==0.3.4
    - iopath==0.1.10
    - itsdangerous==2.2.0
    - Jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.3.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - kiwisolver==1.4.5
    - langchain==0.2.11
    - langchain-core==0.2.23
    - langchain-text-splitters==0.2.2
    - langsmith==0.1.93
    - lazy_loader==0.3
    - lightning==2.3.3
    - lightning-utilities==0.11.5
    - linkify-it-py==2.0.2
    - lit==17.0.6
    - lvis==0.5.3
    - Markdown==3.5.1
    - markdown-it-py==2.2.0
    - MarkupSafe==2.1.3
    - matplotlib==3.7.4
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - networkx==3.1
    - numpy==1.23.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - open-clip-torch==2.17.1
    - opencv-contrib-python==4.3.0.36
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - orjson==3.10.6
    - packaging==23.2
    - pandas==2.0.3
    - paramiko==3.4.0
    - pfzy==0.3.4
    - Pillow==9.4.0
    - pkgutil_resolve_name==1.3.10
    - platformdirs==4.2.2
    - portalocker==2.8.2
    - prettytable==3.10.2
    - prompt_toolkit==3.0.47
    - protobuf==3.20.3
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pyarrow==17.0.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycares==4.4.0
    - pycocotools==2.0.7
    - pycparser==2.22
    - pydantic
    - pydantic-extra-types
    - pydantic-settings
    - pydantic_core
    - pydeck==0.9.1
    - pyDeprecate==0.3.1
    - pydub==0.25.1
    - Pygments==2.18.0
    - PyNaCl==1.5.0
    - pyparsing==3.1.1
    - pyre-extensions==0.0.23
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-multipart==0.0.6
    - pytorch-lightning==1.5.0
    - pytz==2023.3.post1
    - PyWavelets==1.4.1
    - PyYAML==6.0.1
    - qudida==0.0.4
    - redis==5.0.7
    - referencing==0.32.0
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.7.1
    - rpds-py==0.13.2
    - rsa==4.9
    - runpod==1.6.2
    - s3transfer==0.10.2
    - safetensors==0.2.7
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy
    - segment-anything==1.0
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - share==1.0.4
    - shellingham==1.5.4
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - SQLAlchemy==2.0.31
    - st-star-rating==0.0.6
    - starlette==0.27.0
    - streamlit==1.36.0
    - streamlit-drawable-canvas==0.9.3
    - streamlit-js-eval==0.1.7
    - streamlit-star-ratings==0.0.1
    - submitit==1.5.1
    - supervision==0.21.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.5.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.4.0
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - timm==0.6.12
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.13.0
    - toolz==0.12.0
    - torch==2.0.0
    - torchmetrics
    - torchvision==0.15.1
    - tornado==6.4.1
    - tqdm==4.65.0
    - tqdm-loggable==0.2
    - transformers==4.19.2
    - triton==2.0.0
    - typer==0.12.3
    - typing-inspect==0.9.0
    - typing_extensions==4.9.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - ujson==5.10.0
    - urllib3
    - uvicorn==0.24.0.post1
    - uvloop==0.19.0
    - watchdog==4.0.1
    - watchfiles==0.22.0
    - wcwidth==0.2.12
    - websockets==11.0.3
    - Werkzeug==3.0.1
    - xformers==0.0.18
    - yacs==0.1.8
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.17.0
    - imageio-ffmpeg==0.4.2
    - test-tube>=0.7.5
    - webdataset==0.2.5
    - kornia==0.6
    - invisible-watermark>=0.1.5
    - basicsr==1.4.2
    - torch-fidelity
    - bezier
    - diffusers==0.12.1
    - pudb==2019.2
    - hydra-core